define([
    // "skylark-utils-dom/query",
    // "./affix",
    // "./alert",
    // "./button",
    "skylark-bootstrap3/carousel",
    "./checkbox",
    "./collapse",
    "./combobox",
    "./datepicker",
    "skylark-bootstrap3/dropdown",
    // "./dropdown-autoflip",
    // "./infinite-scroll",
    "skylark-bootstrap3/modal",
    // "./picker",
    // "./pillbox",
    // "./placard",
    // "./popover",
    // "./radio",
    //"./repeater",
    //"./repeater-list",
    //"./repeater-thumbnail",
    // "./scheduler",
    // "./scrollspy",
    "./search",
    "./selectlist",
    // "./spinbox",
    "skylark-bootstrap3/tab",
    // "./toolbar",
    // "./tooltip",
    "skylark-bootstrap3/transition",
    // "./tree",
    // "./window",
    "./wizard",
    // "./lightbox"
], function($) {
    return $;
});